<?php
$servername = 'localhost';
$username = 'test';
$password = 'test';
$dbname = 'mydb';

$conn = new mysqli($servername, $username, $password, $dbname);

if ($conn->connect_error) {
	die("connection_failed:". $conn->connect_error);
}



$sql = "CREATE TABLE BOOK (BOOKID INT(11), TITLE varchar(30) NOT NULL, PUBLISHER_NAME varchar(30) NOT NULL, PRIMARY KEY(BOOKID));";

$sql .= "CREATE TABLE BOOK_AUTHORS (BOOKID INT(11), AUTHOR_NAME varchar(30) NOT NULL, PRIMARY KEY(BOOKID,AUTHOR_NAME));";

$sql .= "CREATE TABLE PUBLISHER (PNAME varchar(30) NOT NULL, ADDRESS varchar(30), PHONE INT(11), PRIMARY KEY(PNAME));";

$sql .= "CREATE  TABLE  BOOK_COPIES (BOOKID INT(11), BRANCH_ID INT(11) NOT NULL, NO_OF_COPIES INT(11) NOT NULL , PRIMARY KEY(BOOKID, BRANCH_ID));";

$sql .= "CREATE TABLE BOOK_LOANS (BOOKID INT(11),BRANCH_ID INT(11) NOT NULL, CARD_NO INT(11) NOT NULL, DATE_OUT DATE, DUE_DATE DATE, PRIMARY KEY(BOOKID, BRANCH_ID, CARD_NO));";


$sql .= "CREATE TABLE LIBRARY_BRANCH (BRANCH_ID INT(11) NOT NULL, BRANCH_NAME varchar(30), ADDRESS varchar(30), PRIMARY KEY(BRANCH_ID));";

$sql .= "CREATE TABLE BORROWER (CARD_NO INT(11) NOT NULL, BNAME varchar(30) NOT NULL, ADDRESS varchar(30) NOT NULL, PHONE INT(11) NOT NULL, PRIMARY KEY(CARD_NO));";






$sql .= "ALTER TABLE BOOK_AUTHORS ADD CONSTRAINT BOOKID_FK FOREIGN KEY(BOOKID) REFERENCES BOOK(BOOKID) INITIALLY DEFERRED DEFERRABLE;";

$sql .= "ALTER TABLE BOOK_COPIES ADD CONSTRAINT BOOK_COPIES_BOOKID_FK FOREIGN KEY(BOOKID) REFERENCES BOOK(BOOKID) INITIALLY DEFERRED DEFERRABLE;";


$sql .= "ALTER TABLE BOOK_LOANS ADD CONSTRAINT BOOK_LOANS_BOOKID_FK FOREIGN KEY(BOOKID) REFERENCES BOOK(BOOKID) INITIALLY DEFERRED DEFERRABLE;";


$sql .= "ALTER TABLE BOOK ADD CONSTRAINT PUBLISHER_NAME_FK FOREIGN KEY(PUBLISHER_NAME) REFERENCES PUBLISHER(PNAME) INITIALLY DEFERRED DEFERRABLE;";


$sql .= "ALTER TABLE BOOK_LOANS ADD CONSTRAINT CARD_NO_FK FOREIGN KEY(CARD_NO) REFERENCES BORROWER(CARD_NO)INITIALLY DEFERRED DEFERRABLE;";

$sql .= "ALTER TABLE BOOK_LOANS ADD CONSTRAINT LIBRARY_BRANCH_ID_FK FOREIGN KEY(BRANCH_ID) REFERENCES LIBRARY_BRANCH(BRANCH_ID)INITIALLY DEFERRED DEFERRABLE;";
$sql .= "ALTER TABLE BOOK_COPIES ADD CONSTRAINT BOOK_COPIES_BRANCH_ID_FK FOREIGN KEY(BRANCH_ID) REFERENCES LIBRARY_BRANCH(BRANCH_ID) INITIALLY DEFERRED DEFERRABLE;";
$sql .= "COMMIT";





if($conn->multi_query($sql) == TRUE){
	echo 'Value Inserted SUCCESSFULLY';
}
else{
	echo 'Error in Row Insertion ' . $conn->error;
}

$conn->close();





?>