-- Q8
SELECT EMPNO ,ENAME,(SAL*15/100) AS INCREMENT_,(SAL*15/100 + SAL) AS NEW_SALARY,SAL FROM EMP;

--Q9
SELECT ENAME,(NVL2(COMM,TO_CHAR(COMM),TO_CHAR('NO COMMISION'))) FROM EMP;

--Q10
SELECT ENAME,HIREDATE,TO_CHAR(HIREDATE,'DAY') AS WEEK FROM EMP;

--Q11
SELECT INITCAP(ENAME) AS NAME_,LENGTH(ENAME) AS LENGTH_ FROM EMP WHERE SUBSTR(ENAME,0,1) = 'J' OR SUBSTR(ENAME,0,1) = 'M' OR SUBSTR(ENAME,0,1) = 'A';   

--Q12
SELECT ENAME,HIREDATE,TO_CHAR(SYSDATE,'YYYY') - TO_CHAR(HIREDATE,'YYYY') AS DURATION FROM EMP WHERE TO_CHAR(SYSDATE,'YYYY') - TO_CHAR(HIREDATE,'YYYY') > 35;

--Q13
SELECT SUM(SAL) AS TOTAL_SALARY FROM EMP;

--Q14
select DEPTNO,COUNT(*) AS TOTAL_EMP_DEPARTMENT FROM EMP GROUP BY deptno;

--Q15
select DEPTNO,COUNT(*) AS TOTAL_EMP_DEPARTMENT FROM EMP GROUP BY deptno HAVING MAX(SAL) > 2900;

--Q16
select DEPTNO,COUNT(*) AS TOTAL_EMP_DEPARTMENT FROM EMP GROUP BY deptno HAVING COUNT(*) > 3;