SET SERVEROUTPUT ON;
--
--DECLARE 
--V_cOUNT
--
--
--BEGIN
--V_cOUNTER := &V_cOUNTER;
--LOOP
--V_COUNTER := V_COUNTER + 1;
--DBMS_OUTPUT.PUT_LINE('19'||'X'||V_COUNTER);
--EXIT WHEN V_COUNTER >= 20;
--END LOOP;
--
--END;

--QUES1

DECLARE 
NUM1 NUMBER;
NUM2 NUMBER;
ANS NUMBER;

BEGIN
NUM1 := &NUM1;
NUM2 := &NUM2;
ANS := NUM1 + NUM2;

DBMS_OUTPUT.PUT_LINE(NUM1||'+'||NUM2||' = '|| ANS);
END;
/

--QUES2
DECLARE 
NUM1 NUMBER;
NUM2 NUMBER;
ANS NUMBER;

BEGIN
NUM1 := &NUM1;
NUM2 := &NUM2;
ANS :=0;
LOOP
ANS := ANS+ NUM1;
NUM1 := NUM1+1;
EXIT WHEN NUM1=NUM2+1;
END LOOP;

DBMS_OUTPUT.PUT_LINE('SUM : '||ANS);
END;

/
--QUES3
DECLARE 
ENO EMP.EMPNO%TYPE;
NAME EMP.ENAME%TYPE;
HIREDATE  EMP.HIREDATE%TYPE;
DEPTNAME DEPT.DNAME%TYPE;


BEGIN
ENO := &ENO;
SELECT E.ENAME,E.HIREDATE,D.DNAME INTO NAME,HIREDATE,DEPTNAME FROM EMP E, DEPT D WHERE EMPNO = ENO AND D.DEPTNO = E.DEPTNO ;
DBMS_OUTPUT.PUT_LINE(NAME ||' , ' ||HIREDATE ||' , ' ||DEPTNAME );
END;
/

--QUES 4
DECLARE 
NUM  NUMBER;
REVNUM NUMBER;
TEMPNUM NUMBER;

BEGIN
NUM := &NUM;
REVNUM := 0;
TEMPNUM := NUM;
LOOP
REVNUM := (REVNUM*10) + (TEMPNUM MOD 10);
TEMPNUM := FLOOR(TEMPNUM / 10);

EXIT WHEN TEMPNUM = 0;
END LOOP;
DBMS_OUTPUT.PUT_LINE(REVNUM);

IF REVNUM = NUM THEN
DBMS_OUTPUT.PUT_LINE(REVNUM||' IS PALINDROME');
ELSE
DBMS_OUTPUT.PUT_LINE(REVNUM||' IS NOT PALINDROME');
END IF;

END;

/

-- QUES 5
DECLARE 
ENO EMP.EMPNO%TYPE;
FNAME EMP.ENAME%TYPE;
HIREDATE  EMP.HIREDATE%TYPE;
SAL EMP.SAL%TYPE;
DNO EMP.DEPTNO%TYPE;
COMM EMP.COMM%TYPE;
MGR EMP.MGR%TYPE;
JOB EMP.JOB%TYPE;


BEGIN
ENO := &ENO;
FNAME := '&FNAME';
HIREDATE := TO_DATE('&HIREDATE');
SAL := '&SAL';
DNO := &DNO;
COMM := '&COMM';
MGR := &MGR;
JOB := '&JOB';
--ENO := 7854;
--FNAME := 'HASSAN';
--HIREDATE := TO_DATE('06/SEP/2018');
--DBMS_OUTPUT.PUT_LINE(HIREDATE);
--SAL := '56';
--DNO := 2;
--COMM := '2';
--MGR := 7839;
--JOB := 'CLERK';

INSERT INTO EMP E (E.EMPNO,E.ENAME,E.HIREDATE, E.SAL,E.DEPTNO,E.COMM,E.MGR,E.JOB ) VALUES(ENO,FNAME,HIREDATE,SAL,DNO,COMM,MGR,JOB);

DBMS_OUTPUT.PUT_LINE(FNAME ||' , ' ||HIREDATE ||' , ');
END;


/
--QUES 6
DECLARE 
ENO EMP.EMPNO%TYPE;
FNAME EMP.ENAME%TYPE;
HIREDATE  EMP.HIREDATE%TYPE;
SAL EMP.SAL%TYPE;
DNO EMP.DEPTNO%TYPE;
COMM EMP.COMM%TYPE;
MGR EMP.MGR%TYPE;
JOB EMP.JOB%TYPE;
TEMPNO EMP.SAL%TYPE;


BEGIN



TEMPNO:=7499;


LOOP

--SELECT E.ENAME,E.SAL,E.EMPNO,E.MGR INTO FNAME,SAL,ENO,MGR FROM EMP E WHERE E.EMPNO=TEMPNO AND E.SAL >= 2500;
SELECT E.ENAME,E.SAL,E.EMPNO,E.MGR INTO FNAME,SAL,ENO,MGR FROM EMP E WHERE E.EMPNO=TEMPNO;

IF SAL >= 2500 THEN
DBMS_OUTPUT.PUT_LINE(FNAME ||' , MANAGER :' ||MGR ||' , EMPNO:'|| ENO||', SAL : '||SAL);
EXIT ;
END IF;

TEMPNO := MGR;



EXIT WHEN TEMPNO IS NULL;
END LOOP;

END;


/
--QUES 7
DECLARE 
NUM1 NUMBER;
NUM2 NUMBER;
ANS NUMBER;

BEGIN
NUM1 := 0;
NUM2 := 100;
ANS :=0;
LOOP
ANS := ANS+ NUM1;
NUM1 := NUM1+1;
EXIT WHEN NUM1=NUM2+1;
END LOOP;

DBMS_OUTPUT.PUT_LINE('SUM OF 100 NUMBERS : '||ANS);
END;
/



